global:
  secretName: "app/dev/mongodb-credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: ccfc63c2e91eb03bf7a4385fdc9f53e78ede6d65
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
