global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 5bb753550339d08ece75e11541057ff88cfd9ad1
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
