global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 7806e7b76bc132164485c2cd3e59029b700e057e
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
