global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 2b91bc755a68d5403d58da3f5fad715279f98fc5
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
