global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 023e5737e994bda53925f0b0c1cb4f6f943d40ed
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
