global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 0be1f5ea17bc5a901893566f145b849cb113bac1
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
