global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 87bdd24d74d5adde118eb7dbd3c46de099dfc89e
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
