global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 98bde45af109e557810f8d434141506c07e62c93
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
