global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 320738861cd1ba2d1723e269d762c868c4b3dfb5
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
