global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 4f9d0d06c451a095c03b705f58f4ddbdff0d3239
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
