global:
  secretName: "app/dev/mongodb-credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 6dc7421f36c52eb5c7b70a019d81e4e451f236a7
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
