global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: ad671ca34fcef83fea5e2258caa7853c216d2439
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
