global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 45817fefec8cb3392a8e1c59358d3fe9eedd50da
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
