global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 93b57e3f53e67c473c0e8f600b50ddb3a2115de5
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
