global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 7d86b53d87074c170a40906cb08ae98d0abe6519
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
