global:
  secretName: "MongoDB-Credentials"
app:
  image:
    repository: 825765414083.dkr.ecr.us-east-2.amazonaws.com/dev/app
    tag: 228b48a9ef5a88b4b8ab0f38dd365fb2a0d666fc
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  replicaCount: 1
